# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chunking_pb2 as chunking__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chunking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChunkingServiceStub(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/chunking.ChunkingService/ProcessDocument',
                request_serializer=chunking__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=chunking__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.EnqueueDocument = channel.unary_unary(
                '/chunking.ChunkingService/EnqueueDocument',
                request_serializer=chunking__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=chunking__pb2.EnqueueDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocumentStatus = channel.unary_unary(
                '/chunking.ChunkingService/GetDocumentStatus',
                request_serializer=chunking__pb2.GetDocumentStatusRequest.SerializeToString,
                response_deserializer=chunking__pb2.GetDocumentStatusResponse.FromString,
                _registered_method=True)
        self.GetCards = channel.unary_unary(
                '/chunking.ChunkingService/GetCards',
                request_serializer=chunking__pb2.GetCardsRequest.SerializeToString,
                response_deserializer=chunking__pb2.GetCardsResponse.FromString,
                _registered_method=True)
        self.GetQuiz = channel.unary_unary(
                '/chunking.ChunkingService/GetQuiz',
                request_serializer=chunking__pb2.GetQuizRequest.SerializeToString,
                response_deserializer=chunking__pb2.GetQuizResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/chunking.ChunkingService/Search',
                request_serializer=chunking__pb2.SearchRequest.SerializeToString,
                response_deserializer=chunking__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/chunking.ChunkingService/DeleteDocument',
                request_serializer=chunking__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=chunking__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/chunking.ChunkingService/HealthCheck',
                request_serializer=chunking__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=chunking__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.IngestCurriculum = channel.unary_unary(
                '/chunking.ChunkingService/IngestCurriculum',
                request_serializer=chunking__pb2.IngestCurriculumRequest.SerializeToString,
                response_deserializer=chunking__pb2.IngestCurriculumResponse.FromString,
                _registered_method=True)
        self.GetCurriculum = channel.unary_unary(
                '/chunking.ChunkingService/GetCurriculum',
                request_serializer=chunking__pb2.GetCurriculumRequest.SerializeToString,
                response_deserializer=chunking__pb2.GetCurriculumResponse.FromString,
                _registered_method=True)
        self.SearchByLearningOutcome = channel.unary_unary(
                '/chunking.ChunkingService/SearchByLearningOutcome',
                request_serializer=chunking__pb2.SearchByLearningOutcomeRequest.SerializeToString,
                response_deserializer=chunking__pb2.SearchByLearningOutcomeResponse.FromString,
                _registered_method=True)
        self.GenerateCurriculumQuiz = channel.unary_unary(
                '/chunking.ChunkingService/GenerateCurriculumQuiz',
                request_serializer=chunking__pb2.GenerateCurriculumQuizRequest.SerializeToString,
                response_deserializer=chunking__pb2.GetQuizResponse.FromString,
                _registered_method=True)


class ChunkingServiceServicer(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    def ProcessDocument(self, request, context):
        """Sync: nhận file bytes → parse → chunk → embed → lưu Qdrant + MinIO → trả kết quả ngay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueDocument(self, request, context):
        """Async: upload file → enqueue BullMQ job → trả về ngay với document_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentStatus(self, request, context):
        """Poll trạng thái job async
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCards(self, request, context):
        """Lấy lesson cards đã generate cho document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuiz(self, request, context):
        """Lấy quiz questions đã generate cho document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Semantic search qua vector similarity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Xóa toàn bộ chunks của một document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check — kiểm tra service còn sống không
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestCurriculum(self, request, context):
        """---------------------------------------------------------------------------
        Curriculum-Aware layer
        ---------------------------------------------------------------------------

        Parse DCMH → extract LO graph → persist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurriculum(self, request, context):
        """Lấy curriculum đã ingest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByLearningOutcome(self, request, context):
        """Search chunks theo LO / chapter / assessment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCurriculumQuiz(self, request, context):
        """Sinh quiz aligned theo LO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=chunking__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=chunking__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'EnqueueDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueDocument,
                    request_deserializer=chunking__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=chunking__pb2.EnqueueDocumentResponse.SerializeToString,
            ),
            'GetDocumentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentStatus,
                    request_deserializer=chunking__pb2.GetDocumentStatusRequest.FromString,
                    response_serializer=chunking__pb2.GetDocumentStatusResponse.SerializeToString,
            ),
            'GetCards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCards,
                    request_deserializer=chunking__pb2.GetCardsRequest.FromString,
                    response_serializer=chunking__pb2.GetCardsResponse.SerializeToString,
            ),
            'GetQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuiz,
                    request_deserializer=chunking__pb2.GetQuizRequest.FromString,
                    response_serializer=chunking__pb2.GetQuizResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=chunking__pb2.SearchRequest.FromString,
                    response_serializer=chunking__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=chunking__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=chunking__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=chunking__pb2.HealthCheckRequest.FromString,
                    response_serializer=chunking__pb2.HealthCheckResponse.SerializeToString,
            ),
            'IngestCurriculum': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestCurriculum,
                    request_deserializer=chunking__pb2.IngestCurriculumRequest.FromString,
                    response_serializer=chunking__pb2.IngestCurriculumResponse.SerializeToString,
            ),
            'GetCurriculum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurriculum,
                    request_deserializer=chunking__pb2.GetCurriculumRequest.FromString,
                    response_serializer=chunking__pb2.GetCurriculumResponse.SerializeToString,
            ),
            'SearchByLearningOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByLearningOutcome,
                    request_deserializer=chunking__pb2.SearchByLearningOutcomeRequest.FromString,
                    response_serializer=chunking__pb2.SearchByLearningOutcomeResponse.SerializeToString,
            ),
            'GenerateCurriculumQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCurriculumQuiz,
                    request_deserializer=chunking__pb2.GenerateCurriculumQuizRequest.FromString,
                    response_serializer=chunking__pb2.GetQuizResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chunking.ChunkingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chunking.ChunkingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkingService(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/ProcessDocument',
            chunking__pb2.ProcessDocumentRequest.SerializeToString,
            chunking__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/EnqueueDocument',
            chunking__pb2.ProcessDocumentRequest.SerializeToString,
            chunking__pb2.EnqueueDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/GetDocumentStatus',
            chunking__pb2.GetDocumentStatusRequest.SerializeToString,
            chunking__pb2.GetDocumentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/GetCards',
            chunking__pb2.GetCardsRequest.SerializeToString,
            chunking__pb2.GetCardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/GetQuiz',
            chunking__pb2.GetQuizRequest.SerializeToString,
            chunking__pb2.GetQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/Search',
            chunking__pb2.SearchRequest.SerializeToString,
            chunking__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/DeleteDocument',
            chunking__pb2.DeleteDocumentRequest.SerializeToString,
            chunking__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/HealthCheck',
            chunking__pb2.HealthCheckRequest.SerializeToString,
            chunking__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestCurriculum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/IngestCurriculum',
            chunking__pb2.IngestCurriculumRequest.SerializeToString,
            chunking__pb2.IngestCurriculumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurriculum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/GetCurriculum',
            chunking__pb2.GetCurriculumRequest.SerializeToString,
            chunking__pb2.GetCurriculumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByLearningOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/SearchByLearningOutcome',
            chunking__pb2.SearchByLearningOutcomeRequest.SerializeToString,
            chunking__pb2.SearchByLearningOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCurriculumQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/GenerateCurriculumQuiz',
            chunking__pb2.GenerateCurriculumQuizRequest.SerializeToString,
            chunking__pb2.GetQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
