# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.delivery.grpc.proto import chunking_pb2 as chunking__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chunking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChunkingServiceStub(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/chunking.ChunkingService/ProcessDocument',
                request_serializer=chunking__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=chunking__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/chunking.ChunkingService/Search',
                request_serializer=chunking__pb2.SearchRequest.SerializeToString,
                response_deserializer=chunking__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/chunking.ChunkingService/DeleteDocument',
                request_serializer=chunking__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=chunking__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/chunking.ChunkingService/HealthCheck',
                request_serializer=chunking__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=chunking__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ChunkingServiceServicer(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    def ProcessDocument(self, request, context):
        """Nhận file bytes → parse → chunk → embed → lưu Qdrant + MinIO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Semantic search qua vector similarity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Xóa toàn bộ chunks của một document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check — kiểm tra service còn sống không
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=chunking__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=chunking__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=chunking__pb2.SearchRequest.FromString,
                    response_serializer=chunking__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=chunking__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=chunking__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=chunking__pb2.HealthCheckRequest.FromString,
                    response_serializer=chunking__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chunking.ChunkingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chunking.ChunkingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkingService(object):
    """---------------------------------------------------------------------------
    ChunkingService — document processing + semantic search
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/ProcessDocument',
            chunking__pb2.ProcessDocumentRequest.SerializeToString,
            chunking__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/Search',
            chunking__pb2.SearchRequest.SerializeToString,
            chunking__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/DeleteDocument',
            chunking__pb2.DeleteDocumentRequest.SerializeToString,
            chunking__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chunking.ChunkingService/HealthCheck',
            chunking__pb2.HealthCheckRequest.SerializeToString,
            chunking__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
